### ISSUE TITLE
Login always fails

### ISSUE THREAD

**Issue by MTRNord** [ananace/ruby-matrix-sdk#1]
First of all: I am a Ruby beginner (first day trying it) so it might be me being dumb.

When it tries to Login the Error is always:

```
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/matrix_sdk-0.0.3/lib/matrix_sdk/api.rb:648:in `block in print_http': undefined method `replace' for nil:NilClass (NoMethodError)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/matrix_sdk-0.0.3/lib/matrix_sdk/api.rb:648:in `each'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/matrix_sdk-0.0.3/lib/matrix_sdk/api.rb:648:in `print_http'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/matrix_sdk-0.0.3/lib/matrix_sdk/api.rb:613:in `block in request'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/matrix_sdk-0.0.3/lib/matrix_sdk/api.rb:610:in `loop'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/matrix_sdk-0.0.3/lib/matrix_sdk/api.rb:610:in `request'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/matrix_sdk-0.0.3/lib/matrix_sdk/api.rb:191:in `login'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/matrix_sdk-0.0.3/lib/matrix_sdk/client.rb:87:in `login'
        from C:/Users/marce/RubymineProjects/node_alert/main.rb:32:in `prepare_matrix'
        from C:/Users/marce/RubymineProjects/node_alert/main.rb:10:in `initialize'
        from C:/Users/marce/RubymineProjects/node_alert/main.rb:86:in `new'
        from C:/Users/marce/RubymineProjects/node_alert/main.rb:86:in `<main>'
```

The code is:
```
hs_url = config['Matrix']['homeserver']
@client = MatrixSdk::Client.new hs_url
puts 'Logging in on Matrix...'
@client.login(config['mxid'], config['passwd'], no_sync: true)
```

This is in the above in the stacktrace named function `prepare_matrix`. The config fields all return strings. homeserver is present and filled with `https://matrix.ffslfl.net` (other config values are obviously private)

**Comment by ananace** [comment]
Well, that error happens because the password ends up being passed as a nil value into the request, which - while it's not allowed in the spec - really shouldn't crash the code.

**Comment by ananace** [comment]
Threw in some validation into the client abstraction as well now, which should hopefully generate a better exception message.

**Comment by MTRNord** [comment]
Oh I now even See what I did wrong which caused Nil in the first place :) I should have slept more
