### ISSUE TITLE
Crashes if initial sync fails because of a timeout

### ISSUE THREAD

**Issue by MTRNord** [ananace/ruby-matrix-sdk#2]
Hi back with another error :)

```
DEBUG  MatrixSdk::Api : >
C:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/ruby-matrix-sdk-c5a1c98661c9/lib/matrix_sdk/api.rb:628:in `block in request': #<Net::HTTPGatewayTimeOut:0x0000000004202570> (MatrixSdk::MatrixConnectionError)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/ruby-matrix-sdk-c5a1c98661c9/lib/matrix_sdk/api.rb:610:in `loop'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/ruby-matrix-sdk-c5a1c98661c9/lib/matrix_sdk/api.rb:610:in `request'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/ruby-matrix-sdk-c5a1c98661c9/lib/matrix_sdk/api.rb:126:in `sync'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/ruby-matrix-sdk-c5a1c98661c9/lib/matrix_sdk/client.rb:248:in `sync'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/ruby-matrix-sdk-c5a1c98661c9/lib/matrix_sdk/client.rb:102:in `login'
DEBUG  MatrixSdk::Api : < Received a 504 Gateway Time-out response:
        from C:/Users/marce/RubymineProjects/node_alert/main.rb:31:in `prepare_matrix'
        from C:/Users/marce/RubymineProjects/node_alert/main.rb:10:in `initialize'
DEBUG  MatrixSdk::Api : < server: nginx/1.13.3
        from C:/Users/marce/RubymineProjects/node_alert/main.rb:92:in `new'
DEBUG  MatrixSdk::Api : < date: Mon, 20 Aug 2018 11:53:22 GMT
        from C:/Users/marce/RubymineProjects/node_alert/main.rb:92:in `<main>'
DEBUG  MatrixSdk::Api : < content-type: text/html
DEBUG  MatrixSdk::Api : < content-length: 183
DEBUG  MatrixSdk::Api : < connection: keep-alive
DEBUG  MatrixSdk::Api : <
```

seems like it crashes if gateway timeout happens on initial sync

**Comment by ananace** [comment]
Actually, I'm not sure if this should be considered a bug or an improvement request.

What should happen if the initial sync fails? Should the client just loudly ignore that the sync failed and act as if you hadn't requested an initial sync in the first place? Should the client retry the initial sync until it succeeds? Should the client limit scope and attempt a quicker sync?

I get the feeling that throwing an exception might actually the the right thing to do here, though maybe the exception should be wrapped into a more easily caught type.

**Comment by MTRNord** [comment]
Yeah I think it makes sense to tell it how often it is allowed to retry. I dont know any better option for now except for handling it outside of the sdk itself

**Comment by ananace** [comment]
Added support for sending `allow_sync_retry` into login - and

**Comment by MTRNord** [comment]
Awesome thanks :)
